server:
  addr: :5001
  certificate: /path/to/server.pem 
  key: /path/to/server.key
token:
  issuer: Acme auth server
  expiration: 900
users:
  "": {}
ldap_auth:
  addr: ldap.example.com:389
  tls: true
  base: o=example.com
  filter: (&(uid=${account})(objectClass=person))
  # in case bind DN and password is required for querying directory server
  bind_dn:
  bind_password_file:
acl:
- match:
    account: ""
  actions: [pull]
- match:
    account: /.+/
  actions: ['*']
